// require('admin-lte/plugins/jquery/jquery')
// require('admin-lte/plugins/bootstrap/js/bootstrap.bundle')
// require('admin-lte/plugins/overlayScrollbars/js/OverlayScrollbars.js')
// require('admin-lte/plugins/bs-stepper/js/bs-stepper.js')
// require('admin-lte/plugins/select2/js/select2.js')
// require('admin-lte/plugins/bootstrap-switch/js/bootstrap-switch.js')
require('admin-lte/plugins/datatables/jquery.dataTables.min.js')
require('admin-lte/plugins/datatables-responsive/js/dataTables.responsive.js')
